

# This file was *autogenerated* from the file rsa.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_53 = Integer(53); _sage_const_59 = Integer(59)
import random

def pub(p, q):
	n = p * q
	relative_primes_arr = n.coprime_integers(n)
	rnd_idx = random.randrange(_sage_const_0 , len(relative_primes_arr))
	return (n, relative_primes_arr[rnd_idx]) 

def euler(p, q):
	return (p - _sage_const_1 ) * (q - _sage_const_1 )

P = _sage_const_53 
Q = _sage_const_59 

print("Select two primes: P = " + str(P) + " Q = " + str(Q))
N, e = pub(P, Q)
print("Public key is: N = " + str(N) + " e = " + str(e))

phi = euler(P, Q)
print(phi)

d = inverse_mod(e, phi)

